# Generated by Django 4.1.1 on 2022-09-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managementapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="phone",),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.IntegerField(default=5000),
        ),
    ]
